<?php

namespace AppBundle\Repository;

/**
 * FitxategiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FitxategiaRepository extends \Doctrine\ORM\EntityRepository
{
}
